# wrangler.toml
name = "gemini-proxy-panel"
main = "worker/src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "public"

[observability]
enabled = true

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "fa76c6b496e444bea8390c7d1c64ddcc"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "4f4b99fdc3fe40d3a34f3f859b0aa7ba"
